### ISSUE TITLE
add support for role property and signUpDate

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-satismeter#1]
_From @wcjohnson11 on March 27, 2015 16:16_

[Noodle wants](https://segment.zendesk.com/agent/tickets/26290) Satismeter updated to pass a `role` property and wants to know how to pass through `signUpDate` which is currently from [user().created()](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/satismeter/index.js#L61-L63) but our spec shows as [createdAt](https://segment.com/docs/spec/identify/#traits).

_Copied from original issue: segmentio/analytics.js-integrations#574_

**Comment by hankim813** [comment]
closed for inactivity -- please reopen if still an issue
